version: '3.7'

services:

  mysql:
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: songs
    ports:
      - 3306:3306